# Generated by Django 3.0.1 on 2022-10-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantdifficulty',
            options={'verbose_name_plural': 'Plant difficulties'},
        ),
    ]
